### ISSUE TITLE
为毛我滚动不了？？

### ISSUE THREAD

**Issue by moz1q1** [RexSuper/RichEditor#10]
`<FrameLayout
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/dp_90"
                        android:layout_marginLeft="@dimen/dp_16"
                        android:layout_marginTop="@dimen/dp_10"
                        android:layout_marginRight="@dimen/dp_16"
                        android:focusable="true"
                        android:focusableInTouchMode="true">

                        <requestFocus />
                        
                        

                        <com.rex.editor.view.RichEditorNew
                            android:id="@+id/richEditorTitle"
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                            android:background="@color/color_F7F7F7"
                            android:padding="@dimen/dp_10" />

                        <TextView
                            android:id="@+id/tv_title_tip"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_alignParentRight="true"
                            android:layout_alignParentBottom="true"
                            android:layout_gravity="right|bottom"
                            android:padding="@dimen/dp_5"
                            android:text="0/20"
                            android:textColor="@color/color_999999"
                            android:textSize="@dimen/sp_14" />
                    </FrameLayout>`

**Comment by RexSuper** [comment]
他本质就是个Webview，你可以看看你这个布局里面webview是否能滚动，内容是否超出了屏幕

**Comment by RexSuper** [comment]
> 他本质就是个Webview，你可以看看你这个布局里面webview是否能滚动，内容是否超出了屏幕



> `
> 
> ```
>                     <requestFocus />
>                     
>                     
> 
>                     <com.rex.editor.view.RichEditorNew
>                         android:id="@+id/richEditorTitle"
>                         android:layout_width="match_parent"
>                         android:layout_height="match_parent"
>                         android:background="@color/color_F7F7F7"
>                         android:padding="@dimen/dp_10" />
> 
>                     <TextView
>                         android:id="@+id/tv_title_tip"
>                         android:layout_width="wrap_content"
>                         android:layout_height="wrap_content"
>                         android:layout_alignParentRight="true"
>                         android:layout_alignParentBottom="true"
>                         android:layout_gravity="right|bottom"
>                         android:padding="@dimen/dp_5"
>                         android:text="0/20"
>                         android:textColor="@color/color_999999"
>                         android:textSize="@dimen/sp_14" />
>                 </FrameLayout>`
> ```

1

**Comment by moz1q1** [comment]
是我搞错了，我外面还嵌套nsv

**Comment by RexSuper** [comment]
> 是我搞错了，我外面还嵌套nsv

好的
