### ISSUE TITLE
请请问在编辑的时候，如何获取图片或者视频view,然后添加删除图标或者二次编辑图片的操作

### ISSUE THREAD

**Issue by guangzq** [RexSuper/RichEditor#11]
您好，请问在编辑的时候，如何获取图片或者视频view,然后添加删除图标或者二次编辑图片的操作，比如像知乎这样
![image](https://user-images.githubusercontent.com/19594348/70323697-7661ae80-1868-11ea-8c25-935c0b7b7268.png)

**Comment by Duanjiadong** [comment]
兄弟，，你那边获取选中文字状态粗体，下划线等等能获取成功么？是哪个方法？

**Comment by RexSuper** [comment]
> 兄弟，，你那边获取选中文字状态粗体，下划线等等能获取成功么？是哪个方法？

onConsoleMessage 里面会输出一部分

**Comment by RexSuper** [comment]
> 您好，请问在编辑的时候，如何获取图片或者视频view,然后添加删除图标或者二次编辑图片的操作，比如像知乎这样
> ![image](https://user-images.githubusercontent.com/19594348/70323697-7661ae80-1868-11ea-8c25-935c0b7b7268.png)

这里面整个是webview，加载的html一个带编辑框的网页，每添加一个图片其实是添加的一段html代码标签。你要自定义只能源码集成集成，添加图片的时候使用的标签，然后修改<image>这样的标签 自定义去实现

**Comment by guangzq** [comment]
好的，感谢回复~
